name: almusafir_direct
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.2+2

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  http: ^1.2.2
  geolocator: ^13.0.4
  google_maps_flutter: ^2.7.0

  # Bloc for state management
  flutter_bloc: ^9.1.0
  # Functional programming things
  dartz: ^0.10.1
  #  # Value equality
  equatable: ^2.0.5
  #  # Service locator
  get_it: ^8.0.3
  # Remote API
  internet_connection_checker_plus: ^2.5.2
  pinput: ^5.0.0

  awesome_dialog: ^3.2.1
  shared_preferences: ^2.2.3

  firebase_messaging: ^15.2.3
  firebase_core: ^3.2.0

  url_launcher: ^6.3.0
  flutter_local_notifications: ^19.1.0
  location: ^8.0.0
  fluttertoast: ^8.2.12

  cached_network_image: ^3.3.1
  flutter_staggered_animations: ^1.1.1

  flutter_keyboard_visibility: ^6.0.0
  lottie: ^3.1.2
  intl: ^0.20.2
  permission_handler: ^12.0.0+1
  iconsax_flutter: ^1.0.0
  image: ^4.3.0
  path: ^1.9.0

  win32: ^5.9.0
  carousel_slider: ^5.0.0
  shimmer: ^3.0.0
  upgrader: ^11.3.2
  image_picker: ^1.1.2
  image_cropper: ^9.1.0
  dio: ^5.8.0+1
  share_plus: ^11.0.0
  bloc_concurrency: ^0.3.0
  flutter_rating_bar: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.11
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: DINNextLTArabicBold
      fonts:
        - asset: assets/fonts/ArbFONTS-DINNextLTArabic-Bold-2.ttf
    - family: DINNEXTLTARABICLIGHT
      fonts:
        - asset: assets/fonts/ArbFONTS-DINNEXTLTARABIC-LIGHT-1.ttf
    - family: DINNextLTArabicMedium
      fonts:
        - asset: assets/fonts/ArbFONTS-DINNextLTArabic-Medium-2.ttf
    - family: DINNextLTArabicRegular
      fonts:
        - asset: assets/fonts/ArbFONTS-DINNextLTArabic-Regular-2.ttf
    - family: DINNextLTArabicUltraLight
      fonts:
        - asset: assets/fonts/ArbFONTS-DINNextLTArabic-UltraLight-1.ttf
    - family: ShamelBook
      fonts:
        - asset: assets/fonts/FF-Shamel-Family-Sans-One-Book.ttf
    - family: ShamelBold
      fonts:
        - asset: assets/fonts/FF-Shamel-Family-Sans-One-Bold.ttf

  assets:
    - assets/images/
    - assets/icons/
    - assets/lottie/
    - assets/fonts/
    - assets/json/countries.json
